name: cafeteriauth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.2.6
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3 # --- PAQUETE AÃ‘ADIDO PARA GUARDAR DATOS ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#42a5f5"
    image: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
